modified code EDEX - merge remotes/origin/ncep_14.4.1 to upc development
Former-commit-id: a5f122276598ed8faccfe5a6ecf52b5031668084

diff --git a/edexOsgi/com.raytheon.uf.tools.cli/impl/capture b/edexOsgi/com.raytheon.uf.tools.cli/impl/capture
--- a/edexOsgi/com.raytheon.uf.tools.cli/impl/capture
+++ b/edexOsgi/com.raytheon.uf.tools.cli/impl/capture
@@ -2,10 +2,9 @@
 # base path to save capture data to, will create subdirectory for each workstation
 basePath="/data/fxa/cave"
 
-# the grep string to find the cave processes
-grepString="(/awips2/cave/cave|/usr/local/viz/cave)"
-
 edexGrepString="edex.run.mode="
+
+xorgLogPath="/var/log"
 
 # the remote servers to grab top on.  Use to get general state of servers
 REMOTE_SERVERS_TO_CHECK="${DX_SERVERS}"
@@ -30,6 +29,7 @@ GRAB_REMOTE_VMSTAT="Y"
 GRAB_CAVE_AND_ALERTVIZ_LOGS="Y"
 GRAB_SCREENSHOT="Y"
 GRAB_CURRENT_QUERIES="Y"
+GRAB_XORG_LOG="Y"
 EDEX_MODE="N"
 FORCE="N"
 TGZ_OUTPUT="Y"
@@ -48,16 +48,13 @@ usage() {
    echo "  The servers to grab top information from, make sure list is quoted and space delimited"
    echo
    echo -e "-d {y/n}\t\tdefault [$RUN_JMAP]"
-   echo "  Run jmap to grab the head dump information"
+   echo "  Run jmap to grab the heap dump information"
    echo
    echo -e "-e {request/ingest/ingestGrib/ingestDat}"
    echo "  Run edex mode and grab information about the jvm passed.  May be used multiple times to grab data about multiple jvms"
    echo
    echo -e "-f {y/n}\t\tdefault [$FORCE]"
    echo "  Force a jstack/jmap by default"
-   echo
-   echo -e "-g {grep string}\tdefault [$grepString]"
-   echo "  The grep string used to find the processes"
    echo
    echo -e "-l {y/n}\t\tdefault [$GRAB_CAVE_AND_ALERTVIZ_LOGS]"
    echo "  Captures the cave and alertviz logs.  If run for a specific pid the only cave log captured will be for that pid"
@@ -132,6 +129,21 @@ checkYes() {
    fi
 }
 
+#check if at least 1 GB of free mem exists to run jmap
+checkJmapMem() {
+   CAP_MEM=1000
+   let freeMem=`free -m |grep buffers/cache|awk '{print $4}'`
+
+   if [ $freeMem -gt $CAP_MEM ]; then
+       echo "${t1}: ${freeMem}M free, running jmap" >> $processFile
+       return 1
+   else
+       echo "${t1}: ${freeMem}M free, skipping jmap" >> $processFile
+       return 0
+   fi
+}
+
+
 # runs import to grab screen shot of users desktop
 grabScreenShot() {
    if [ "$GRAB_SCREENSHOT" == "y" ]; then
@@ -147,6 +159,16 @@ grabScreenShot() {
             let "count+=1"
          fi
       done
+   fi
+}
+
+# runs import to grab screen shot of users desktop
+grabXorgLog() {
+   if [ "$GRAB_XORG_LOG" == "y" ]; then
+      echo "Capturing Xorg logs"
+      t1=`date "+%Y%m%d %H:%M:%S"`
+      echo "${t1}: Capturing Xorg logs" >> $processFile
+      cp ${xorgLogPath}/Xorg*.log* ${dataPath} >> $processFile 2>&1 &
    fi
 }
 
@@ -184,6 +206,7 @@ grabCurrentDatabaseQueries() {
       t1=`date "+%Y%m%d %H:%M:%S"`
       echo "${t1}: Capturing current database queries" >> $processFile
       out_file="${dataPath}/database_queries.log"
+      echo "dx1f:5432:metadata:awips:awips" > ~/.pgpass; chmod 600 ~/.pgpass
       psql -d metadata -U awips -h ${DATABASE_HOST} -c "select datname, pid, client_addr, query, now()-xact_start as runningTime from pg_stat_activity where state != 'idle' order by runningTime desc;" >>  $out_file 2>&1 &
    fi
 }
@@ -319,23 +342,32 @@ runJmap() {
    local t1=`date "+%Y%m%d %H:%M:%S"`
    local log="${prePath}dump.log"
    local dumpPath="${prePath}dump"
+   local heapPath="${prePath}heap"
 
    if [ "$ACCUM" == "y" ]; then
       # accum needs to change hprof by date
       local t2=`date "+%Y%m%d_%H%M%S"`
       dumpPath="${dumpPath}_${t2}.hprof"
+      heapPath="${heapPath}_${t2}.txt"
    else
       dumpPath="${dumpPath}.hprof"
+      heapPath="${heapPath}.txt"
    fi
 
-   local cmd="/awips2/java/bin/jmap -dump:format=b,file=${dumpPath}"
-   echo "${t1}: Running command: $cmd $options $pid >> $log 2>&1 &" >> $processFile
-   $cmd $options $pid >> $log 2>&1 &
+   echo "${t1}: Running command: /awips2/java/bin/jmap -heap $pid" >> $processFile
+   /awips2/java/bin/jmap -heap $pid >> ${heapPath} 2>&1
+
+   # Java 1.7 has a bug that causes jmap to crash processes using the G1 garbage collector
+   # more info at http://stackoverflow.com/questions/20571004/garbage-collector-first-and-jmap-eof-bug
+   # workaround is to add the 'live' option to jmap to limit the dump to only live objects
+   local cmd="/awips2/java/bin/jmap -dump:live,format=b,file=${dumpPath}"
+   echo "${t1}: Running command: $cmd $options $pid >> $log 2>&1" >> $processFile
+   $cmd $options $pid >> $log 2>&1
 
    if [[ "$?" != "0" && $FORCE != "y" ]]; then
       t1=`date "+%Y%m%d %H:%M:%S"`
       echo "${t1}: jmap for $pid failed to connect, rerunning with -F" >> $processFile
-      $cmd $options -F $pid >> $log 2>&1 &
+      $cmd $options -F $pid >> $log 2>&1
    fi
 }
 
@@ -391,6 +423,35 @@ runVersions() {
    $cmd >> ${dataPath}/versions.log 2>&1
 }
 
+# take in pid, output process name without args
+getCommandName() {
+    ps --no-header c -p $1 -o cmd
+}
+
+# take in pid, output parent process id
+getParentPid() {
+    ps --no-header -p $1 -o ppid
+}
+
+# take in pid, output associated cave executable pid if found, otherwise output given pid
+determineCaveProcess() {
+   local RVAL=$1
+   # check if supplied PID is for the cave executable
+   local CMD_NAME=$(getCommandName $1)
+   if [[ ! $CMD_NAME =~ cave ]]
+   then
+       # worker pid probably provided, check parent
+       RVAL=$(getParentPid $1)
+       if [[ ! $(getCommandName $RVAL) =~ cave ]]
+       then
+           # parent wasn't cave either... continue on using PID provided
+           echo "${t1}: Unable to find cave process for pid $1, proceeding with provided PID" >> $processFile
+           RVAL=$1
+       fi
+   fi
+   echo $RVAL
+}
+
 # parse command line
 while [ ! -z "$1" ]; do
    arg=$1
@@ -401,7 +462,6 @@ while [ ! -z "$1" ]; do
       -d) RUN_JMAP="$1"; shift 1;;
       -e) EDEX_MODE="Y"; edexProcs[$edexProcCount]="$1"; shift 1; let "edexProcCount+=1";;
       -f) FORCE="$1"; shift 1;;
-      -g) grepString="$1"; shift 1;;
       -l) GRAB_CAVE_AND_ALERTVIZ_LOGS="$1"; shift 1;;
       -m) MOVE_ALL_HS_ERR_PID="$1"; shift 1;;
       -p) cavePid="$1"; shift 1;;
@@ -433,6 +493,7 @@ checkYes TGZ_OUTPUT $TGZ_OUTPUT
 checkYes ACCCUM $ACCCUM
 checkYes RUN_VERSIONS $RUN_VERSIONS
 checkYes GRAB_SCREENSHOT $GRAB_SCREENSHOT
+checkYes GRAB_XORG_LOG $GRAB_XORG_LOG
 
 # if PID mode don't grab other hs_err_pids
 if [ ! -z $cavePid ]; then
@@ -451,6 +512,7 @@ if [ "$EDEX_MODE" == "y" ]; then
    MOVE_ALL_HS_ERR_PID="n"
    GRAB_REMOTE_TOP="n"
    GRAB_REMOTE_VMSTAT="n"
+   GRAB_XORG_LOG="n"
 fi
 
 umask 0002
@@ -506,9 +568,26 @@ if [ "$EDEX_MODE" == "y" ]; then
    done
 
    grepString="${grepString}) "
+   procs=`ps -ef | grep -E "$grepString" | grep -v "grep"`
+else
+   #list of cave process ids to get ps output for
+   caveProcNums=""
+   for parent in $(pgrep '^cave$')
+   do
+       # the cave process starts a new JVM as a child process
+       # find all children of the cave process
+       children=$(pgrep -P $parent)
+       if [[ -z $children ]]
+       then
+           # no children, assume that this is a main cave process
+           caveProcNums="$caveProcNums $parent"
+       else
+           # otherwise, only get ps output for children
+           caveProcNums="$caveProcNums $children"
+       fi
+   done
+   procs=$(ps --no-header -fp $caveProcNums)
 fi
-
-procs=`ps -ef | grep -E "$grepString" | grep -v "grep" | grep -v "cave.sh"`
 
 if [ ! -z "$cavePid" ]; then
    # limit cave procs to the requested PID
@@ -545,13 +624,22 @@ if [ ! -z "${myProcs}" ]; then
    IFS=$PREV_IFS
 
    launchJstacks
-   launchJmaps
+
+   checkJmapMem
+   let rc=$?
+   if [ $rc -eq 1 ]; then 
+       launchJmaps
+   fi
+
 else
    t1=`date "+%Y%m%d %H:%M:%S"`
    echo "*** NO processes found for user $user, capturing limited data to $dataPath"
    echo "${t1}: NO processes found for $user" >> $processFile
    echo "" >> $processFile
 fi
+
+# grab Xorg logs
+grabXorgLog
 
 # grab top for servers
 grabRemoteTop
@@ -630,7 +718,8 @@ if [ "${GRAB_CAVE_AND_ALERTVIZ_LOGS}" == "y" ]; then
       echo "${t1}: Capturing cave logs" >> $processFile
       mkdir -p ${dataPath}/consoleLogs
       if [ ! -z ${cavePid} ]; then
-         find $dir  -type f -name "*${cavePid}*" -exec cp {} ${dataPath}/consoleLogs \;
+         # logs have cave executable pid or worker pid in the name (-o means OR)
+         find $dir  -type f -name "*$(determineCaveProcess ${cavePid})*" -o -name "*${cavePid}*" -exec cp {} ${dataPath}/consoleLogs \;
       else
          find $dir  -type f -mmin -120 -exec cp {} ${dataPath}/consoleLogs \;
       fi
@@ -671,6 +760,7 @@ fi
 zenity --info --no-wrap --title="Capture Done" --text="$message" > /dev/null 2>&1 &
 echo
 echo $message
+rm ~/.pgpass
 
 cd $curDir
 
