13.1.2-6 baseline
Former-commit-id: 750f03f60223eeb17b561c4c98926dffd31db737 [formerly 1d4d25b49b54f901c9620278b2e9e685119e3203] [formerly efd3392abe82bda657e1b0294f1d4aea3ea07f7e] [formerly efd3392abe82bda657e1b0294f1d4aea3ea07f7e [formerly 8e5f9e0e6cd71836ba4a5942340171ffd9dfed36]] [formerly 750f03f60223eeb17b561c4c98926dffd31db737 [formerly 1d4d25b49b54f901c9620278b2e9e685119e3203] [formerly efd3392abe82bda657e1b0294f1d4aea3ea07f7e] [formerly efd3392abe82bda657e1b0294f1d4aea3ea07f7e [formerly 8e5f9e0e6cd71836ba4a5942340171ffd9dfed36]] [formerly 59969775adb93e7480b5f273c3a4221085358227 [formerly efd3392abe82bda657e1b0294f1d4aea3ea07f7e [formerly 8e5f9e0e6cd71836ba4a5942340171ffd9dfed36] [formerly 59969775adb93e7480b5f273c3a4221085358227 [formerly 184f16c9f91fb06efa7aeaf5499ace33f4f17bf7]]]]]
Former-commit-id: 59969775adb93e7480b5f273c3a4221085358227
Former-commit-id: 7058edde32424c47a248daa09c87d312c9bc60df [formerly fe763963e9abc7c338f876da08a945e7408013b8] [formerly 82a1ed77a49cd86eff27606a6b523b4ade30d55c] [formerly e0da2714c31e9f48ef47551baeecd5541fe2e224 [formerly fa884fbcd584330564fea44a1538e11036e753a8] [formerly 82a1ed77a49cd86eff27606a6b523b4ade30d55c [formerly dbcae57f57f284e2bbf3dd5dba56899801053574]]]
Former-commit-id: f1899c432c7f194616c4f9d49b19f53f87a0c962 [formerly 385d5b42196eb703cc60637c47506c02c454b5fc] [formerly b7f180d9d3c53e04fe7b2fbc2f793e43121558c1 [formerly 05bdc0ecd21b62dd2b59e21c8288546ac30880ac]]
Former-commit-id: b7f180d9d3c53e04fe7b2fbc2f793e43121558c1
Former-commit-id: 3e63f280a2bb1ee2ae426032d51aeccc93b43b5b

diff --git a/edexOsgi/com.raytheon.uf.tools.gfesuite.servicebackup/svcBackup/ServiceBackup/scripts/export_grids b/edexOsgi/com.raytheon.uf.tools.gfesuite.servicebackup/svcBackup/ServiceBackup/scripts/export_grids
--- a/edexOsgi/com.raytheon.uf.tools.gfesuite.servicebackup/svcBackup/ServiceBackup/scripts/export_grids
+++ b/edexOsgi/com.raytheon.uf.tools.gfesuite.servicebackup/svcBackup/ServiceBackup/scripts/export_grids
@@ -118,13 +118,18 @@ perform_export() {
 	  #check if the netcdf file is there;if not,exit
 	  if [ $? -ne 0 ]
 	  then
-	      $LOGGER "ifpnetCDF failed. Export exits."
-	      rm -f ${lockFile}
-	      $LOGGER 100
 	      NETCDF_SUCCESS=0
 	      if [ $NATIONAL_CENTER != 1 ] && [ "$1" != "-c" ] 
 	      then
-	          exit 1
+		netcdf_error=`grep "Some of the requested time ranges are not in the inventory" $logfile`
+                if [ "$netcdf_error" != "" ]; then
+                    NETCDF_SUCCESS=1
+                else
+		    $LOGGER "ifpnetCDF failed. Export exits."
+                    rm -f ${lockFile}
+                    $LOGGER 100
+                    exit 1
+                fi
               fi
 	  fi
       else
@@ -136,13 +141,18 @@ perform_export() {
 	  #check if the netcdf file is there;if not,exit
 	  if [ $? -ne 0 ]
 	  then
-	      $LOGGER "ifpnetCDF failed. Export exits."
-	      rm -f ${lockFile}
-	      $LOGGER 100
 	      NETCDF_SUCCESS=0
 	      if [ $NATIONAL_CENTER != 1 ] && [ "$1" != "-c" ]
-              then	
-	          exit 1
+              then
+		netcdf_error=`grep "Some of the requested time ranges are not in the inventory" $logfile`
+                if [ "$netcdf_error" != "" ]; then
+                  NETCDF_SUCCESS=1
+                else
+		  $LOGGER "ifpnetCDF failed. Export exits."
+                  rm -f ${lockFile}
+                  $LOGGER 100
+                  exit 1
+                fi
 	      fi	
 	  fi
       fi
@@ -153,14 +163,19 @@ perform_export() {
       #check if the netcdf file is there;if not,exit before we call msg_send
       if [ $? -ne 0 ]
       then
-		$LOGGER ifpnetCDF failed.
-		rm -f ${lockFile}
-		$LOGGER 100
-		NETCDF_SUCCESS=0
-		if [ $NATIONAL_CENTER != 1 ] && [ "$1" != "-c" ]
-                then
-		    exit 1
-		fi
+	NETCDF_SUCCESS=0
+	if [ $NATIONAL_CENTER != 1 ] && [ "$1" != "-c" ]
+        then
+	  netcdf_error=`grep "Some of the requested time ranges are not in the inventory" $logfile`
+	  if [ "$netcdf_error" != "" ]; then
+	    NETCDF_SUCCESS=1
+	  else
+	    $LOGGER "ifpnetCDF failed."
+            rm -f ${lockFile}
+            $LOGGER 100
+	    exit 1
+	  fi
+	fi
       fi
   fi
 
