Omaha #4103: Update GFE service backup server code to support multiple service backup sites, use "smarter" lock files to store additional status.
NOTE: Service Backup features are broken until DR 4300 lands on this branch.

Change-Id: Ic0184c10c553187c8d0515f639c5a33fd3abde1f

Former-commit-id: a4d13dbabde92b91bb9053be1016b5ef21a8dd04 [formerly 732208b6600882a9ba9fcc0eefd7c8be0157beab]
Former-commit-id: fd5b270fddfe2898947b04dc5a9ac81784ff55f4

diff --git a/edexOsgi/com.raytheon.uf.tools.gfesuite.servicebackup/svcBackup/ServiceBackup/scripts/receive_grids b/edexOsgi/com.raytheon.uf.tools.gfesuite.servicebackup/svcBackup/ServiceBackup/scripts/receive_grids
--- a/edexOsgi/com.raytheon.uf.tools.gfesuite.servicebackup/svcBackup/ServiceBackup/scripts/receive_grids
+++ b/edexOsgi/com.raytheon.uf.tools.gfesuite.servicebackup/svcBackup/ServiceBackup/scripts/receive_grids
@@ -19,13 +19,16 @@
 # further licensing information.
 ##
 ##############################################################################
-# TODO: ADD DESCRIPTION
+# This script is triggered by MHS when the requested failed site's grids are
+# sent to the backup site.
 #
 #     SOFTWARE HISTORY
 #    
 #    Date            Ticket#       Engineer       Description
 #    ------------    ----------    -----------    --------------------------
 #    05/10/11        8688          dgilling       Initial Creation.
+#    02/12/15        4103          dgilling       Pre-emptively determine site id.
+#
 ##############################################################################
 
 # this allows you to run this script from outside of ./bin
@@ -36,6 +39,7 @@ BASE_AWIPS_DIR=`dirname $RUN_FROM_DIR`
 
 # get the base environment
 source /awips2/GFESuite/bin/setup.env
+source /awips2/GFESuite/ServiceBackup/scripts/serviceBackupUtil.sh
 
 # setup the environment needed to run the the Python
 export LD_LIBRARY_PATH=${PYTHON_INSTALL}/lib
@@ -45,6 +49,27 @@ export PYTHONPATH=${RUN_FROM_DIR}/src:$PYTHONPATH
 _PYTHON="${PYTHON_INSTALL}/bin/python"
 _MODULE="/awips2/GFESuite/ServiceBackup/scripts/receive_grids.py"
 
-# quoting of '$@' is used to prevent command line interpretation 
-$_PYTHON $_MODULE -h localhost -r 9581 "$@"
+RECEIVED_FILE=${1}
+if [[ -f ${RECEIVED_FILE} ]]
+then
+	SITE_ID=$(getSiteIdFromTarFile "${RECEIVED_FILE}")
+    if [[ -z "${SITE_ID}" ]]
+    then
+    	#Still need to do this the old way for backward compatibility
+		tar -tvf ${import_file} | while read line
+		do
+			echo "Using old tar/cut method."
+		    echo "line is $line"
+		    # Can we get rid of this ugly thing somehow???
+		    SITE_ID=`echo $line | cut -d' ' -f8|cut -d'G' -f1|cut -d'/' -f6`
+		    echo "failed site $SITE_ID"
+		    break
+		done
+	fi
+else
+	echo "Unable to locate the gridded data of failed site: ${import_file}. You will need to initialize your grids from models and guidance"
+	exit 1
+fi
+
+$_PYTHON $_MODULE -h localhost -r 9581 ${RECEIVED_FILE} ${SITE_ID}
 
